config/routes.rb
Rails.application.routes.draw do

  get '/favourites', to: "favourites#index"
  root to: "pages#home"
  resources :properties do
    resources :bookings, only: :create
    resources :favourites, only: [:create, :destroy]
  end
  resources :bookings, except: [:new, :create] do 
     resources :reviews, only: :create 
  end

  resources :bookings, except: [:new, :create] do 
     resources :reviews, only: :create 
  end
 
  resources :reviews, except: [:new, :create]
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "users/:user_id/bookings", to: "bookings#users_index", as: :user_bookings
  get "users/:user_id/properties", to: "properties#users_index", as: :user_properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :property
  has_many :reviews
  validates :number_of_guests, presence: true # , numericality: { less_than_or_equal_to: :property.total_occupancy }
  validates :status, inclusion: { in: %w(Pending Approved Declined), message: "%{value} is not a valid value" }, allow_nil: true
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :favourites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many_attached :photos, dependent: :destroy
  geocoded_by :address
  validates :name, presence: true
  validates :property_type, presence: true
  validates :total_occupancy, presence: true, numericality: { only_integer: true }
  validates :summary, presence: true
  validates :price_per_night, presence: true, numericality: { only_float: true }
  validates :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :property
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
  
  # def errormessage
  #   if content.blank? || rating.blank?
  #     errors.add(:content, :rating "please make sure you completed the form correctly.")
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :favourites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :destroy, :update]

  def new # Louis
    @booking = Booking.new(start_date: Date.today)
  end

  def create # Louis
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.property_id = params[:property_id]
    @booking.status = "Pending"
    @property = Property.find(params[:property_id])
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render "properties/show"
    end
  end

  def show # Yunus
    @review = Review.new
  end

  def edit # Alex
  end

  def update # Alex
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def index # Jake
    @bookings = current_user.bookings
    @properties = current_user.properties
  end

  def destroy # Yunus
    @booking.destroy
    redirect_to root_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_cost, :price_per_night, :number_of_guests, :status)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.select("property_id").where(user_id: current_user.id)
    
    @properties = Property.where(id: @favourites)
    
    @markers = @properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { property: property }),
        image_url: helpers.asset_path("map-pin.svg")
      }
    end
    @search_success = true
    render 'properties/index'
  end

  def create
    @favourite = Favourite.new
    @favourite.user = current_user
    @favourite.property = Property.find(params[:property_id])
    @favourite.save
  end
  
  def destroy
    @favourite = Favourite.where(property_id: params[:id], user_id: current_user.id).first
    @favourite.destroy
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.name = @property.name.capitalize
    @property.user = current_user
    if @property.save
      redirect_to property_path(@property)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
  end

  def destroy
    @property.destroy
    redirect_to user_properties_path(@property.user_id)
  end

  def users_index
    @properties = current_user.properties
  end

  def index
    @search_success = true
    unless @properties
      if params[:query].present?
        coordinates = Geocoder.search(params[:query]).first.coordinates
        @properties = Property.near(coordinates, 50)
        if @properties.empty?
          @search_success = false
          @properties = Property.all
        end
      else
        @properties = Property.all
      end
    end
    
    @markers = @properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { property: property }),
        image_url: helpers.asset_path("map-pin.svg")
      }
    end
  end

  def edit
  end

  def update
    if @property.update(property_params)
      redirect_to property_path(@property)
    else
      render :edit
    end
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name, :property_type, :total_occupancy, :total_bedrooms, :total_bathrooms,
     :summary, :price_per_night, :has_tv, :has_kitchen, :has_aircon,
     :has_heating, :has_internet, :address, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_review, only: [:edit, :destroy, :update]
  def edit # no need to write anything inside due to before action
    @booking = @review.booking
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking =  @booking
    @review.property = @booking.property
    if @review.save
      redirect_to booking_path(@booking)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def update
    @booking = @review.booking
    @review.update(review_params)
    redirect_to booking_path(@booking)
  end
  
  def destroy 
    @booking = @review.booking
    @review.destroy
    redirect_to booking_path(@booking)
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <h1>Edit a booking</h1>
  <%= render 'booking_form', property: @property, booking: @booking %>
</div>

app/views/bookings/index.html.erb
<div class="container col-md-8">

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active pink" data-toggle="tab" href="#my-bookings-tab">Bookings</a>
    </li>
    <li class="nav-item">
      <a class="nav-link pink"  data-toggle="tab" href="#property-bookings-tab">Property bookings</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="my-bookings-tab">
      <% if @bookings.empty? %>
        <%= link_to 'Book your first trip now', properties_path, class: "form-button-primary my-5 mx-auto" %>
      <% else %>
      <h2 class='my-3'>My Bookings</h2>
        <% @bookings.each do |booking| %>
          <div class="card-container">
            <div class="card-image-container smaller-image-container">
              <%= cl_image_tag booking.property.photos[0].key, class:"card-image", cloud_name: "dmdajbspi" %>
            </div>
            <div class="card-contents">
              <%= link_to booking.property.name , booking_path(booking), class: "card-title pink" %>
              <% start_date_time_obj = booking.start_date.to_datetime %>
              <% start_date = start_date_time_obj.strftime("%d %B %Y") %>
              <% end_date_time_obj = booking.end_date.to_datetime %>
              <% end_date = end_date_time_obj.strftime("%d %B %Y") %>
              <p class="card-subtitle"><%= start_date %> - <%= end_date %></p>
              <p class='card-details mt-2'><%= booking.property.address %></p>
              <p class='card-details mt-2'><%= booking.property.summary %></p>
              <div class="d-flex justify-content-between"><p class='card-details mt-2'><strong>Status:</strong> <%= booking.status %></p>
              <p class='card-subtitle mt-2'> <strong>Hosted by:</strong> <%= booking.property.user.first_name %> <%= booking.property.user.last_name %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="property-bookings-tab">
      <% if @properties.empty? %>
        <%= link_to "Add a property to get bookings", new_property_path, class: "card-title pink" %>
      <% else %>
      <h2 class='my-3'>My Property Bookings</h2>
        <% @properties.each do |property| %>
          <% property.bookings.each do |booking| %>
            <div class="card-container">
              <div class="card-image-container smaller-image-container">
                <%= cl_image_tag booking.property.photos[0].key, class:"card-image", cloud_name: "dmdajbspi" %>
              </div>
              <div class="card-contents">
                <div class="d-flex justify-content-between">
                <div>
                <%= link_to property.name , property_path(property), class: "card-title pink" %>
                <% start_date_time_obj = booking.start_date.to_datetime %>
                <% start_date = start_date_time_obj.strftime("%d %B %Y") %>
                <% end_date_time_obj = booking.end_date.to_datetime %>
                <% end_date = end_date_time_obj.strftime("%d %B %Y") %>
                <p class="card-subtitle"><%= start_date %> - <%= end_date %></p>
                </div>
              <div>
                <p class='card-details'> <strong>Booked by:</strong> <%= booking.user.first_name %> <%= booking.user.last_name %></p>
              </div>
              </div>
              <p class='card-details mt-2'><%= booking.property.address %></p>
              <p class='card-details'><%= booking.property.summary %></p>
              <div class="d-flex justify-content-between">
                <div>
                  <p><strong>Status:</strong> <%= booking.status %></p>
                </div>
                <% if booking.status != "Pending" && booking.status != "Declined" %>
                  <%= link_to booking_path(id: booking.id, booking: {status: "Declined"}), method: :patch do %>
                    <div class="d-flex align-items-center"><%= image_tag 'x-circle.svg', class: 'favourite-button-red'%> <div><p class="m-0">Cancel</p></div></div>
                  <% end %>
                <% else %>
                  <%= link_to booking_path(id: booking.id, booking: {status: "Approved"}), method: :patch do %>
                    <div class="d-flex align-items-center"><%= image_tag 'check-circle.svg', class: 'favourite-button-red'%><div><p class="m-0">Approve</p></div></div>
                  <% end %>
                  <%= link_to booking_path(id: booking.id, booking: {status: "Declined"}), method: :patch do %>
                    <div class="d-flex align-items-center"><%= image_tag 'x-circle.svg', class: 'favourite-button-red'%> <div><p class="m-0">Cancel</p></div></div>
                  <% end %>
                  
                <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="mx-auto my-4">
    <div class="show-container">
      <span class="show-status-badge">
        <%= @booking.status %>
      </span>
      <h1><%= link_to @booking.property.name, property_path(@booking.property.id), class: "pink" %></h1>
      <div class="show-badges">

        <p class='show-badge'><%= @booking.start_date.to_datetime.strftime("%d %B %Y") %> - <%= @booking.end_date.to_datetime.strftime("%d %B %Y") %> · <%= @booking.property.address %> · <%= @booking.property.user.first_name %>  <%= @booking.property.user.last_name %></p>

      </div>

      <div class="show-image-container">
         <div id="propertyCarousel" class="carousel slide show-image" data-ride="carousel">
          <div class="carousel-inner show-image-border">
            <% counter = 0 %>
            <% @booking.property.photos.each do |photo| %>
              <% if counter == 0 %>
                <div class="carousel-item active">
              <% else %>
                <div class="carousel-item">
                <% end %>
                <%= cl_image_tag photo.key, class:"d-block w-100", cloud_name: "dmdajbspi", style: "object-fit: cover; height: 75vh;" %>
              </div>
              <% counter += 1 %>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#propertyCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#propertyCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div>
          <h3 class='mt-4'>Booking Details</h2>
          <p><%= @booking.property.total_bedrooms %> bedroom<% if @booking.property.total_bedrooms > 1 %>s<% end %> · <%= @booking.property.total_bathrooms %> bathroom<% if @booking.property.total_bathrooms > 1 %>s<% end %></p>
          <p class='show-badge'><%= @booking.property.summary %></p>
          <h4>Amenities</h4>
          <p><% if @booking.property.has_kitchen %> · Kitchen   <% end %>

            <% if @booking.property.has_tv %> · TV   <% end %>

            <% if @booking.property.has_heating %> · Heating   <% end %>

            <% if @booking.property.has_aircon %> · Air con  <% end %></p>
      </div>
      
      <div class="mt-2 py-2 background-color: white justify-content-between" style="border: 2px solid; border-radius: 10px; text-align: center; align-item:center; margin-bottom:15px;">
        <h1>Reviews of the property</h1>
        <% numberofreviews = @booking.reviews.count %>
        <% sumofreviewratings = @booking.reviews.map(&:rating).sum %>
        <% if numberofreviews > 0 %>
          <h2>Overall rating of the property is <%= sumofreviewratings.fdiv(numberofreviews) %> </h2>
          <% else %>
          <h2>This property has not been reviewed yet.</h2>
          <% end %>
        <% @booking.reviews.each do |review| %>
          <div class="mt-2">
            <p><%= review.rating %> stars Reviewed by
              <strong><%="#{review.booking.user.first_name} #{review.booking.user.last_name}"%></strong>
            </p>
          </div>
          <div><%= review.content %></div>
          <% if user_signed_in? && review.booking.user == current_user %>
            <%= link_to "Edit your review", edit_review_path(review) , class: "btn btn-warning"  %>
            <%= link_to "Delete your review", review_path(review), class: "btn btn-danger", method: :delete, data: { confirm: "Remove This review ?" } %>
          <% end %>
        <% end %>
      </div>
      <% if @booking.user == current_user && @booking.reviews.size == 0 %>
        <div class="show-review-form">
          <%= render  partial: 'reviews/review_form', locals: {review: @review, booking: @booking} %>
        </div>
      <% end %>
      <%= link_to "Back to your bookings", bookings_path, class: 'form-button-secondary-text' %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/favourites/index.html.erb
<h1>Favourites#index</h1>
<p>Find me in app/views/favourites/index.html.erb</p>
<% @favourites.each do |fav|%>
  <p><%= link_to fav.property.name, property_path(fav.property) %></p>
<% end %>

app/views/properties/show.html.erb
<div class="container">
  <%= link_to "Back to Properties", properties_path %>
  <div class="d-flex justify-content-between">
    <h1><%= "#{@property.name}"%></h1>
    <% if (current_user.favourite_ids & @property.favourite_ids).any? %>
      <div class="button-container">
        <%= link_to property_favourite_path(@property), method: :delete, remote: true, id: "remove-favourite" do %>
          <%= image_tag 'filled-favourite.svg', class: 'favourite-button-red'%>
        <% end %>
      </div>
    <% else %>
      <div class="button-container">
        <%= link_to property_favourites_path(@property), method: :post, remote: true, id: "add-favourite"  do %>
          <%= image_tag 'favourite.svg', class: 'favourite-button'%>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="container" style="height: 75vh; background-color: white;">
    <div id="propertyCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% counter = 0 %>
        <% @property.photos.each do |photo| %>
          <% if counter == 0 %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
            <% end %>
            <%= cl_image_tag photo.key, class:"d-block w-100", cloud_name: "dmdajbspi", style: "object-fit: cover; height: 75vh;" %>
          </div>
          <% counter += 1 %>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#propertyCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#propertyCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="d-flex flex-wrap justify-content-between">
    <div class="property-details" style="width: 50%; padding: 10px; background-color: white;">
    <div style = "border: 2px solid black; box-shadow: 5px 10px; text-align:center text-align:left; margin-left:2px; padding:2px; border-radius:2px;"> 
      <h3><strong>£<%= @property.price_per_night.round(2) %></strong> / night</h3>
      <p><strong>Hosted by:</strong> <%= @property.user.first_name %> <%= @property.user.last_name %></p>

      <p><%= @property.summary %></p>
      <div class="card-spacer"></div>
      <p><%= @property.address %></p>

      <div class="card-spacer"></div>
      <p>Bedrooms: <%= @property.total_bedrooms %></p>
      <p>Bathrooms: <%= @property.total_bathrooms %></p>
      <p>Max Guests: <%= @property.total_occupancy %></p>
      <div class="card-spacer"></div>
      <ul class="property-feature-list" style="list-style: none;">
        <li <%= @property.has_kitchen ? "" : 'style=color:grey;' %>><%= @property.has_kitchen ? '😊 Has a Kitchen' : '😞 No Kitchen' %></li>
        <li <%= @property.has_internet ? "" : 'style=color:grey;' %>><%= @property.has_internet ? "😊 Has Internet" : "😞 No Internet" %></li>
        <li <%= @property.has_aircon ? "" : 'style=color:grey;' %>><%= @property.has_aircon ? "😊 Has Air Con" : "😞 No Air Con" %></li>
        <li  <%= @property.has_heating ? "" : 'style=color:grey;' %>><%= @property.has_heating ? "😊 Has Heating" : "😞 No Heating" %></li>
      </ul>
      </div>
    </div>
    <% if current_user == @property.user %>
      <div class="owner-controls" style="width: 50%; padding: 10px; background-color: white;">
        <h2>You own this property</h2>
        <%= link_to "Edit", edit_property_path(@property), class: "btn btn-success" %>
        <%= link_to "Delete", property_path(@property), method: "delete", class: "btn btn-danger", data: { confirm: "Remove This Property?" }%>
      <div>
    <% else %>
      <div class="booking-form" style="width: 50%; padding: 10px; background-color: white;">
        <h2>Booking Form</h2>
        <%= render "bookings/booking_form", property: @property, booking: @booking %>
      </div>
    <% end %>
    </div>
     <div class="mt-2 py-2 justify-content-between">
      <h2>Reviews of the property</h2>
      <% numberofreviews = @property.reviews.count %>
      <% sumofreviewratings = @property.reviews.map(&:rating).sum %>
      <% unless @property.reviews.nil? %>
      <h2>Average rating: <%= sumofreviewratings.fdiv(numberofreviews) %> ⭐</h2>
      <% @property.reviews.each do |review| %>
        <div class="review-container my-2">
          <div class="mt-2"> <p><strong><%= review.rating %></strong> ⭐  <strong>Reviewed by</strong>
            <%="#{review.booking.user.first_name} #{review.booking.user.last_name}"%></p>
            </div>
      <div><%= review.content %></div>
    </div>
    <% end %>
     </div>
     <% else %>
    <h2>This property has not been reviewed yet.</h2>
    <% end %>
  </div>
     </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
    <h1>Your review is important for us!</h1>
     <%= render 'review_form', :review => @review  %>
     <%= link_to "Back", bookings_path, class: "btn btn-success" %>
</div>

app/views/shared/_card.html.erb
<div class="card-container">

  <% if property.user == current_user && action_name != "users_index" %>
    <div class="card-ribbon card-ribbon-top-left"><span>Yours</span></div>
  <% end %>

  <div class="card-image-container">

 <%= cl_image_tag property.photos[0].key, class:"card-image", cloud_name: "dmdajbspi" %>

  </div>

  <div class="card-contents">

    <div class="card-badges">

      <div class="card-tabs">
      <% if property.has_internet  %>
        <p class="card-badge">
          WIFI
        </p>
      <% end %>

      <p class="card-supertitle"><%= property.total_bedrooms %> BED<% if property.total_bedrooms > 1 %>S<% end %> · <%= property.total_bathrooms %> BATH<% if property.total_bathrooms > 1 %>S<% end %></p>
</div>
      <div class="card-buttons-container">


        <% if property.user == current_user %>
        <div class="button-container">
          <%= link_to edit_property_path(property) do %>
            <%= image_tag 'edit.svg', class: 'button edit-button'%>
          <% end %>
        </div>
        <% end %>

        <% if property.user == current_user %>
        <div class="button-container">
          <%= link_to property_path(property), method: "delete", data: { confirm: "Remove This Property?" } do%>
            <%= image_tag 'delete.svg', class: 'button delete-button'%>
          <% end %>
        </div>
        <% end %>

        <% if property.user != current_user %>
          <% if (current_user.favourite_ids & property.favourite_ids).any? %>
            <div class="button-container">
              <%= link_to property_favourite_path(property, id: current_user.favourites.where(property_id: property.id).first.id), method: :delete, remote: true, id: "remove-favourite" do %>
                <%= image_tag 'filled-favourite.svg', class: 'favourite-button-red'%>
              <% end %>
            </div>
          <% else %>
            <div class="button-container">
              <%= link_to property_favourites_path(property), method: :post, remote: true, id: "add-favourite"  do %>
                <%= image_tag 'favourite.svg', class: 'favourite-button'%>
              <% end %>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>

    <h2 class='card-title'><%= property.name %></h2>
    <p class='card-subtitle'><%= property.address %></p>

    <div class="card-spacer"></div>

    <div class="card-details">
      <p class='card-subtitle'><% if property.has_kitchen %> · Kitchen   <% end %>

        <% if property.has_tv %> · TV   <% end %>

        <% if property.has_heating %> · Heating   <% end %>

        <% if property.has_aircon %> · Air con  <% end %></p>
      </div>
      <a><%= link_to "View property", property_path(property), class: "card-link"%></a>

      <div class="card-metadata">
        <p class="card-price"><span class="card-price-number">£<%= property.price_per_night %> </span><span class="card-price-unit">/<span class="card-price-small">night</span></span></p>
        <div class="card-reviews">⭐⭐⭐⭐⭐<span class="card-review-count">34 reviews</span></div>
      </div>


    </div>
  </div>

  <script>
    var animateButton = function(e) {

      e.preventDefault;
  //reset animation
  e.target.classList.remove('animate');

  e.target.classList.add('animate');
  setTimeout(function(){
    e.target.classList.remove('animate');
  },700);
};

var classname = document.getElementsByClassName("confetti-button");

for (var i = 0; i < classname.length; i++) {
  classname[i].addEventListener('click', animateButton, false);
}
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/271/cloud-with-rain_1f327-fe0f.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav m-auto">
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Places to stay", properties_path, class: "nav-link" %>
        </li>


        <% if current_user.bookings.size > 0 %>
          <li class="nav-item">
            <%= link_to "Your bookings", bookings_path, class: "nav-link" %>
          </li>
        <% end %>


        <% if current_user.properties.size > 0 %>
          <li class="nav-item">
            <%= link_to "Your properties", "/users/:user_id/properties", class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Host a Home", new_property_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/u/57643651?v=4", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Places", "/properties", class: "dropdown-item" %>
            <%= link_to "Favourites", "/favourites", class: "dropdown-item" %>


            <%= link_to "Bookings", "/bookings", class: "dropdown-item" %>

            <% if current_user.properties.size > 0 %>
              <%= link_to "Properties", "/users/:user_id/properties", class: "dropdown-item" %>
              <% else %>
              <%= link_to "Host a Home", "/properties/new", class: "dropdown-item" %>
            <% end %>


            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Places to stay", properties_path, class: "nav-link mt-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Host a Home", new_property_path, class: "nav-link mt-1" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "sign-in" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "sign-up" %>
        </li>

      <% end %>
    </ul>
  </div>
</div>